//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int IdBillInfo { get; set; }
        public int IdBill { get; set; }
        public int IdFood { get; set; }
        public Nullable<int> IdDrink { get; set; }
        public double Count { get; set; }
        public string IdEmp { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Food Food { get; set; }
    }
}
